"""Interactive setup wizard — ``m365seed setup``.

Walks the user through tenant configuration, theme selection,
content toggles, and config generation.  Optionally validates
and runs a dry-run at the end.
"""

from __future__ import annotations

import os
import re
import shutil
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

console = Console()

# ── Defaults ─────────────────────────────────────────────────
THEMES = ["healthcare", "pharma", "medtech", "payor"]
THEME_LABELS = {
    "healthcare": "Health Provider — clinical ops, care coordination",
    "pharma": "Pharma / Life Science — research, clinical trials",
    "medtech": "MedTech — product dev, manufacturing, 510(k)",
    "payor": "Health Payor — claims, member services",
}

DEFAULT_USERS = [
    {"upn": "AllanDe@{domain}", "role": "Clinical Ops Manager"},
    {"upn": "MeganB@{domain}", "role": "Physician Lead"},
    {"upn": "NestorW@{domain}", "role": "Care Coordinator"},
    {"upn": "LeeG@{domain}", "role": "Nurse Manager"},
    {"upn": "JoniS@{domain}", "role": "Compliance Officer"},
]

CONTENT_SECTIONS = [
    ("mail", "Email threads with attachments", True),
    ("files", "OneDrive / SharePoint files", True),
    ("calendar", "Calendar events", True),
    ("teams", "Teams channels & posts (beta)", False),
    ("chats", "Teams 1:1 and group chats (beta)", False),
    ("sharepoint", "SharePoint sites, pages, docs", False),
    ("planner", "Planner plans, buckets, tasks", False),
]

GUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


# ── Helpers ──────────────────────────────────────────────────


def _ask_guid(label: str, env_var: str | None = None) -> str:
    """Prompt for a GUID, optionally pre-filling from an env var."""
    default = os.environ.get(env_var, "") if env_var else ""
    while True:
        value = Prompt.ask(
            f"  {label}",
            default=default or None,
        )
        if value and GUID_RE.match(value.strip()):
            return value.strip()
        console.print("  [red]Please enter a valid GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).[/red]")


def _ask_choice(label: str, choices: list[str], default: str) -> str:
    """Present numbered choices and return the selection."""
    for i, c in enumerate(choices, 1):
        extra = THEME_LABELS.get(c, "")
        tag = " [dim](default)[/dim]" if c == default else ""
        desc = f" — {extra}" if extra else ""
        console.print(f"    {i}. {c}{desc}{tag}")

    while True:
        raw = Prompt.ask(f"  {label}", default=default)
        stripped = raw.strip()
        # Accept number or name
        if stripped.isdigit():
            idx = int(stripped) - 1
            if 0 <= idx < len(choices):
                return choices[idx]
        if stripped.lower() in [c.lower() for c in choices]:
            return stripped.lower()
        console.print(f"  [red]Choose 1‑{len(choices)} or type a name.[/red]")


def _ask_users(domain: str) -> list[dict[str, str]]:
    """Let the user accept defaults or enter custom UPNs."""
    defaults = [
        {**u, "upn": u["upn"].format(domain=domain)} for u in DEFAULT_USERS
    ]
    console.print("\n  [bold]Default demo users[/bold] (MDX/CDX standard):")
    for u in defaults:
        console.print(f"    • {u['upn']}  ({u['role']})")

    if Confirm.ask("\n  Use these defaults?", default=True):
        return defaults

    users: list[dict[str, str]] = []
    console.print("  Enter users (blank UPN to finish):")
    while True:
        upn = Prompt.ask("    UPN", default="")
        if not upn:
            break
        role = Prompt.ask("    Role", default="Demo User")
        users.append({"upn": upn, "role": role})

    return users if users else defaults


def _generate_config(
    *,
    tenant_id: str,
    client_id: str,
    secret_env: str,
    theme: str,
    run_id: str,
    users: list[dict[str, str]],
    sections: dict[str, bool],
) -> str:
    """Render a complete ``seed-config.yaml`` from wizard answers."""
    lines: list[str] = []
    a = lines.append

    a("# ─────────────────────────────────────────────────────────────")
    a("# M365 Seed — Generated Configuration")
    a("# Generated by: m365seed setup")
    a("# ─────────────────────────────────────────────────────────────")
    a("")
    a("tenant:")
    a(f'  tenant_id: "{tenant_id}"')
    a(f'  authority: "https://login.microsoftonline.com/{tenant_id}"')
    a("")
    a("auth:")
    a('  mode: "client_secret"')
    a(f'  client_id: "{client_id}"')
    a(f'  client_secret_env: "{secret_env}"')
    a("")
    a("targets:")
    a("  users:")
    for u in users:
        a(f'    - upn: "{u["upn"]}"')
        a(f'      role: "{u["role"]}"')
    a("")
    a("content:")
    a(f'  theme: "{theme}"')
    a(f'  run_id: "{run_id}"')
    a("")

    # ── Mail ────────────────────────────────────────────────
    a("mail:")
    if sections.get("mail"):
        a("  threads:")
        a('    - thread_id: "care-coordination-001"')
        a('      subject: "Care Coordination: Discharge planning follow-up"')
        a("      participants:")
        for u in users[:3]:
            a(f'        - "{u["upn"]}"')
        a("      messages: 6")
        a("      include_attachments: true")
        a("")
        a('    - thread_id: "clinical-ops-review-001"')
        a('      subject: "Clinical Ops: Weekly quality metrics review"')
        a("      participants:")
        for u in users[:2]:
            a(f'        - "{u["upn"]}"')
        a("      messages: 4")
        a("      include_attachments: false")
    else:
        a("  threads: []")
    a("")

    # ── Files ───────────────────────────────────────────────
    a("files:")
    a("  oneDrive:")
    a(f"    enabled: {str(sections.get('files', True)).lower()}")
    if sections.get("files") and users:
        a(f'    target_user: "{users[0]["upn"]}"')
    else:
        a('    target_user: ""')
    a("    folders:")
    a('      - "Clinical Ops"')
    a('      - "Care Coordination"')
    a('      - "Compliance"')
    a('      - "Quality Improvement"')
    a("  sharePoint:")
    a("    enabled: false")
    a('    site_id: ""')
    a('    drive_id: ""')
    a("")

    # ── Calendar ────────────────────────────────────────────
    a("calendar:")
    a(f"  enabled: {str(sections.get('calendar', True)).lower()}")
    if sections.get("calendar"):
        a("  events:")
        a('    - event_id: "clinical-ops-standup-001"')
        a('      subject: "Clinical Ops Daily Standup"')
        if users:
            a(f'      organizer: "{users[0]["upn"]}"')
        a("      attendees:")
        for u in users[1:3]:
            a(f'        - "{u["upn"]}"')
        a('      recurrence: "daily"')
        a("      duration_minutes: 15")
        a("      is_online_meeting: true")
    a("")

    # ── Teams ───────────────────────────────────────────────
    a("teams:")
    a(f"  enabled: {str(sections.get('teams', False)).lower()}")
    a('  team_id: ""')
    a("  channels: []")
    a("")

    # ── Chats ───────────────────────────────────────────────
    a("chats:")
    a(f"  enabled: {str(sections.get('chats', False)).lower()}")
    a("  conversations: []")
    a("")

    # ── SharePoint ──────────────────────────────────────────
    a("sharepoint:")
    a(f"  enabled: {str(sections.get('sharepoint', False)).lower()}")
    if sections.get("sharepoint") and users:
        a(f'  owner: "{users[0]["upn"]}"')
    else:
        a('  owner: ""')
    a("  sites: []")
    a("")

    # ── Planner ─────────────────────────────────────────────
    a("planner:")
    a(f"  enabled: {str(sections.get('planner', False)).lower()}")
    a('  group_id: ""')
    a("  plans: []")
    a("")

    return "\n".join(lines)


# ── Main wizard ──────────────────────────────────────────────


def run_setup(config_path: str = "seed-config.yaml") -> None:
    """Interactive setup wizard entry point."""
    console.print(
        Panel.fit(
            "[bold cyan]M365 Demo Tenant Seeding Tool — Setup Wizard[/bold cyan]\n\n"
            "This wizard will walk you through configuring your demo tenant.\n"
            "All values are saved to [bold]seed-config.yaml[/bold].",
            border_style="cyan",
        )
    )

    # ── Step 1: Tenant ──────────────────────────────────────
    console.print("\n[bold]Step 1 — Tenant[/bold]")
    tenant_id = _ask_guid("Tenant ID (GUID)", env_var="M365SEED_TENANT_ID")

    # Derive domain hint from tenant (user can override)
    domain_default = f"M365x{tenant_id[:6]}.onmicrosoft.com"
    domain = Prompt.ask("  Tenant domain", default=domain_default)

    # ── Step 2: App Registration ────────────────────────────
    console.print("\n[bold]Step 2 — App Registration[/bold]")
    auto_register = Confirm.ask(
        "  Register a new app automatically via Azure CLI?", default=False
    )

    secret_env = "M365SEED_CLIENT_SECRET"
    if auto_register:
        from m365seed.register import register_app

        include_sp = sections_preview_sp = Confirm.ask(
            "    Include SharePoint + Planner permissions?", default=True
        )
        include_teams_perms = Confirm.ask(
            "    Include Teams permissions (beta)?", default=False
        )
        reg = register_app(
            tenant_id,
            include_teams=include_teams_perms,
            include_sharepoint_planner=include_sp,
        )
        if reg:
            client_id = reg["client_id"]
            # Set secret in current process env for downstream steps
            os.environ[secret_env] = reg["client_secret"]
            console.print(
                f"\n  [green]✓[/green] App registered — Client ID: [cyan]{client_id}[/cyan]"
            )
            console.print(
                f"  [green]✓[/green] Client secret saved to ${secret_env} for this session."
            )
        else:
            console.print(
                "  [yellow]Auto-registration failed — falling back to manual entry.[/yellow]"
            )
            client_id = _ask_guid("Client (Application) ID", env_var="M365SEED_CLIENT_ID")
    else:
        client_id = _ask_guid("Client (Application) ID", env_var="M365SEED_CLIENT_ID")
        secret_env = Prompt.ask(
            "  Client secret env var name",
            default="M365SEED_CLIENT_SECRET",
        )

    # Verify secret is set
    if not os.environ.get(secret_env):
        console.print(
            f"  [yellow]⚠ Environment variable ${secret_env} is not set.[/yellow]\n"
            f"  Set it before running seed commands:\n"
            f"    export {secret_env}=\"your-client-secret\""
        )

    # ── Step 3: Theme ───────────────────────────────────────
    console.print("\n[bold]Step 3 — Content Theme[/bold]")
    theme = _ask_choice("Select theme", THEMES, default="healthcare")
    console.print(f"  → Theme: [cyan]{theme}[/cyan]")

    # ── Step 4: Run ID ──────────────────────────────────────
    console.print("\n[bold]Step 4 — Run ID[/bold]")
    run_id = Prompt.ask(
        "  Run ID (used for idempotency & cleanup)",
        default="hls-demo-001",
    )

    # ── Step 5: Users ───────────────────────────────────────
    console.print("\n[bold]Step 5 — Demo Users[/bold]")
    users = _ask_users(domain)

    # ── Step 6: Content modules ─────────────────────────────
    console.print("\n[bold]Step 6 — Content Modules[/bold]")
    console.print("  Select which content types to seed:")
    sections: dict[str, bool] = {}
    for key, label, default in CONTENT_SECTIONS:
        sections[key] = Confirm.ask(f"    {label}?", default=default)

    # ── Generate config ─────────────────────────────────────
    yaml_str = _generate_config(
        tenant_id=tenant_id,
        client_id=client_id,
        secret_env=secret_env,
        theme=theme,
        run_id=run_id,
        users=users,
        sections=sections,
    )

    # ── Write config ────────────────────────────────────────
    target = Path(config_path)
    if target.exists():
        overwrite = Confirm.ask(
            f"\n  [yellow]{target} already exists. Overwrite?[/yellow]",
            default=False,
        )
        if not overwrite:
            backup = target.with_suffix(".yaml.bak")
            shutil.copy2(target, backup)
            console.print(f"  Backed up existing config to {backup}")

    target.write_text(yaml_str, encoding="utf-8")
    console.print(f"\n  [green]✓[/green] Wrote [bold]{target}[/bold]")

    # ── Summary ─────────────────────────────────────────────
    table = Table(title="Configuration Summary", show_header=True)
    table.add_column("Setting", style="bold")
    table.add_column("Value")
    table.add_row("Tenant ID", tenant_id)
    table.add_row("Domain", domain)
    table.add_row("Client ID", client_id)
    table.add_row("Secret Env", secret_env)
    table.add_row("Theme", theme)
    table.add_row("Run ID", run_id)
    table.add_row("Users", str(len(users)))
    enabled = [k for k, v in sections.items() if v]
    table.add_row("Content", ", ".join(enabled) or "none")
    console.print()
    console.print(table)

    # ── Next steps ──────────────────────────────────────────
    console.print("\n[bold]Next Steps[/bold]")

    # Offer to validate
    if Confirm.ask("  Run validation now?", default=True):
        console.print()
        _run_child_command(["m365seed", "validate", "-c", str(target)])

    # Offer dry run
    if Confirm.ask("  Run a dry-run seed?", default=True):
        cmd = ["m365seed", "seed-all", "-c", str(target), "--dry-run"]
        if sections.get("teams") or sections.get("chats"):
            cmd.append("--enable-beta-teams")
        console.print()
        _run_child_command(cmd)

    # Offer live run
    if Confirm.ask("  Run the live seed now?", default=False):
        cmd = ["m365seed", "seed-all", "-c", str(target)]
        if sections.get("teams") or sections.get("chats"):
            cmd.append("--enable-beta-teams")
        console.print()
        _run_child_command(cmd)

    console.print(
        "\n[bold green]Setup complete![/bold green] "
        "You can rerun any command individually — see [bold]m365seed --help[/bold]."
    )


def _run_child_command(cmd: list[str]) -> None:
    """Execute an m365seed sub-command, showing output in real time."""
    import subprocess
    import sys

    console.print(f"  [dim]$ {' '.join(cmd)}[/dim]\n")
    try:
        subprocess.run(cmd, check=False)
    except FileNotFoundError:
        # Fall back to module invocation
        subprocess.run(
            [sys.executable, "-m", "m365seed.cli"] + cmd[1:],
            check=False,
        )
